# python train.py --bit 1  --times 1
# python train.py --bit 2  --times 1
# python train.py --bit 3  --times 1
# python train.py --bit 4  --times 1
# python train.py --bit 5  --times 1
# python train.py --bit 6  --times 1
# python train.py --bit 7  --times 1
# python train.py --bit 8  --times 1
# python train.py --bit 9  --times 1
# python train.py --bit 10  --times 1
# python train.py --bit 1  --times 3
# python train.py --bit 2  --times 3
# python train.py --bit 3  --times 3
# python train.py --bit 4  --times 3
# python train.py --bit 5  --times 3
# python train.py --bit 6  --times 3
# python train.py --bit 7  --times 3
# python train.py --bit 8  --times 3
# python train.py --bit 9  --times 3
python train.py --bit 10  --times 3
# python train.py --bit 1  --times 5
# python train.py --bit 2  --times 5
# python train.py --bit 3  --times 5
# python train.py --bit 4  --times 5
# python train.py --bit 5  --times 5
# python train.py --bit 6  --times 5
# python train.py --bit 7  --times 5
# python train.py --bit 8  --times 5
# python train.py --bit 9  --times 5
# python train.py --bit 10  --times 5